---
development:
  cloud_name: dg8u97sn8
  api_key: '786818521864986'
  api_secret: tkNRDO0FTpalz8D6pnIlHbgWQ0w
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dg8u97sn8
  api_key: '786818521864986'
  api_secret: tkNRDO0FTpalz8D6pnIlHbgWQ0w
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dg8u97sn8
  api_key: '786818521864986'
  api_secret: tkNRDO0FTpalz8D6pnIlHbgWQ0w
  enhance_image_tag: true
  static_file_support: false
